import Hamdi from "../../images/Hamdi.jpg";

const StaffData = [
  {
    id: 1,
    name: "Hamdi Arafat",
    title: "MANAGING DIRECTOR / CEO",
    phone: "+30 123 4567832",
    email: "HamdiArafat@gmail.com",
    desc: "MANAGING DIRECTOR / CEO",
    image: Hamdi,
  },
  {
    id: 2,
    name: "John Doe",
    title: "CHIEF OPERATING OFFICER",
    phone: "+30 987 6543210",
    email: "JohnDoe@gmail.com",
    desc: "ACCOUNTING & FINANCE SUPERVISOR",
    image: Hamdi,
  },
  {
    id: 3,
    name: "Hamdi Arafat",
    title: "MANAGING DIRECTOR / CEO",
    phone: "+30 123 4567832",
    email: "HamdiArafat@gmail.com",
    desc: "MANAGING DIRECTOR / CEO",
    image: Hamdi,
  },
  {
    id: 4,
    name: "John Doe",
    title: "CHIEF OPERATING OFFICER",
    phone: "+30 987 6543210",
    email: "JohnDoe@gmail.com",
    desc: "ACCOUNTING & FINANCE SUPERVISOR",
    image: Hamdi,
  },
  {
    id: 5,
    name: "Hamdi Arafat",
    title: "MANAGING DIRECTOR / CEO",
    phone: "+30 123 4567832",
    email: "HamdiArafat@gmail.com",
    desc: "MANAGING DIRECTOR / CEO",
    image: Hamdi,
  },
  {
    id: 6,
    name: "John Doe",
    title: "CHIEF OPERATING OFFICER",
    phone: "+30 987 6543210",
    email: "JohnDoe@gmail.com",
    desc: "ACCOUNTING & FINANCE SUPERVISOR",
    image: Hamdi,
  },
  {
    id: 7,
    name: "Hamdi Arafat",
    title: "MANAGING DIRECTOR / CEO",
    phone: "+30 123 4567832",
    email: "HamdiArafat@gmail.com",
    desc: "MANAGING DIRECTOR / CEO",
    image: Hamdi,
  },
  {
    id: 8,
    name: "John Doe",
    title: "CHIEF OPERATING OFFICER",
    phone: "+30 987 6543210",
    email: "JohnDoe@gmail.com",
    desc: "ACCOUNTING & FINANCE SUPERVISOR",
    image: Hamdi,
  },
  {
    id: 9,
    name: "Hamdi Arafat",
    title: "MANAGING DIRECTOR / CEO",
    phone: "+30 123 4567832",
    email: "HamdiArafat@gmail.com",
    desc: "MANAGING DIRECTOR / CEO",
    image: Hamdi,
  },
  {
    id: 10,
    name: "John Doe",
    title: "CHIEF OPERATING OFFICER",
    phone: "+30 987 6543210",
    email: "JohnDoe@gmail.com",
    desc: "ACCOUNTING & FINANCE SUPERVISOR",
    image: Hamdi,
  },
  {
    id: 11,
    name: "Hamdi Arafat",
    title: "MANAGING DIRECTOR / CEO",
    phone: "+30 123 4567832",
    email: "HamdiArafat@gmail.com",
    desc: "MANAGING DIRECTOR / CEO",
    image: Hamdi,
  },
  {
    id: 12,
    name: "John Doe",
    title: "CHIEF OPERATING OFFICER",
    phone: "+30 987 6543210",
    email: "JohnDoe@gmail.com",
    desc: "ACCOUNTING & FINANCE SUPERVISOR",
    image: Hamdi,
  },
  {
    id: 13,
    name: "Hamdi Arafat",
    title: "MANAGING DIRECTOR / CEO",
    phone: "+30 123 4567832",
    email: "HamdiArafat@gmail.com",
    desc: "MANAGING DIRECTOR / CEO",
    image: Hamdi,
  },
  {
    id: 14,
    name: "John Doe",
    title: "CHIEF OPERATING OFFICER",
    phone: "+30 987 6543210",
    email: "JohnDoe@gmail.com",
    desc: "ACCOUNTING & FINANCE SUPERVISOR",
    image: Hamdi,
  },
  {
    id: 15,
    name: "Hamdi Arafat",
    title: "MANAGING DIRECTOR / CEO",
    phone: "+30 123 4567832",
    email: "HamdiArafat@gmail.com",
    desc: "MANAGING DIRECTOR / CEO",
    image: Hamdi,
  },
  {
    id: 16,
    name: "John Doe",
    title: "CHIEF OPERATING OFFICER",
    phone: "+30 987 6543210",
    email: "JohnDoe@gmail.com",
    desc: "ACCOUNTING & FINANCE SUPERVISOR",
    image: Hamdi,
  },
  {
    id: 17,
    name: "Hamdi Arafat",
    title: "MANAGING DIRECTOR / CEO",
    phone: "+30 123 4567832",
    email: "HamdiArafat@gmail.com",
    desc: "MANAGING DIRECTOR / CEO",
    image: Hamdi,
  },
  {
    id: 18,
    name: "John Doe",
    title: "CHIEF OPERATING OFFICER",
    phone: "+30 987 6543210",
    email: "JohnDoe@gmail.com",
    desc: "ACCOUNTING & FINANCE SUPERVISOR",
    image: Hamdi,
  },
];

export default StaffData;
